# Generated by Django 5.2.9 on 2025-12-27 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=128, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_website', models.CharField(blank=True, max_length=255, null=True)),
                ('company_owner', models.CharField(blank=True, max_length=255, null=True)),
                ('company_iban', models.CharField(blank=True, max_length=64, null=True)),
                ('company_tax_number', models.CharField(blank=True, max_length=64, null=True)),
                ('company_created_at', models.DateTimeField(auto_now_add=True)),
                ('company_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Companie',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_number', models.CharField(max_length=64, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_address', models.TextField(blank=True, null=True)),
                ('customer_vehicle', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_license_plate', models.CharField(blank=True, max_length=32, null=True)),
                ('customer_kilometers', models.PositiveIntegerField(blank=True, null=True)),
                ('customer_created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('diagnosis_id', models.AutoField(primary_key=True, serialize=False)),
                ('diagnosis_title', models.CharField(max_length=255, unique=True)),
                ('diagnosis_default_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('diagnosis_created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'diagnose',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=64, unique=True)),
                ('invoice_order_date', models.DateField()),
                ('invoice_service_date', models.DateField()),
                ('invoice_subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('invoice_vat_percent', models.DecimalField(decimal_places=2, default=19.0, max_digits=5)),
                ('invoice_vat_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('invoice_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('invoice_notes', models.TextField(blank=True, null=True)),
                ('invoice_created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice_customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='invoices.customer')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_item_pos', models.PositiveIntegerField(editable=False)),
                ('invoice_item_diagnosis_text', models.CharField(editable=False, max_length=255)),
                ('invoice_item_quantity', models.PositiveIntegerField(default=1)),
                ('invoice_item_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_item_line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_item_created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_item_updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_item_diagnosis_id', models.ForeignKey(help_text='Select diagnosis from predefined list', on_delete=django.db.models.deletion.PROTECT, to='invoices.diagnosis', verbose_name='Diagnosis Text')),
                ('invoice_item_invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice')),
            ],
            options={
                'ordering': ['invoice_item_pos'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_role', models.CharField(max_length=32)),
                ('profile_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('profile_address', models.TextField(blank=True, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('profile_created_at', models.DateTimeField(auto_now_add=True)),
                ('profile_updated_at', models.DateTimeField(auto_now=True)),
                ('profile_user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
