# Generated by Django 4.2.3 on 2026-02-08 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'verbose_name': 'Diagnosis', 'verbose_name_plural': 'Diagnoses'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ['invoice_item_pos'], 'verbose_name': 'Invoice item', 'verbose_name_plural': 'Invoice items'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterField(
            model_name='company',
            name='company_address',
            field=models.TextField(blank=True, null=True, verbose_name='Company address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Company email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_iban',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Company IBAN'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=255, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_owner',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company owner'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_phone',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Company phone'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_tax_number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Company tax number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_website',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company website'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_address',
            field=models.TextField(blank=True, null=True, verbose_name='Customer address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_kilometers',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Mileage'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_license_plate',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='License plate number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(max_length=255, verbose_name='Customer name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_number',
            field=models.CharField(max_length=64, unique=True, verbose_name='Customer number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_vehicle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vehicle'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis_default_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Default price (€)'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis_title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Diagnosis title'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='invoices.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(max_length=64, unique=True, verbose_name='Invoice number'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_order_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Order date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_service_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Service date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_vat_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='VAT amount'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_vat_percent',
            field=models.DecimalField(decimal_places=2, default=19.0, max_digits=5, verbose_name='VAT (%)'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice_item_diagnosis',
            field=models.ForeignKey(help_text='Select diagnosis from predefined list', on_delete=django.db.models.deletion.PROTECT, to='invoices.diagnosis', verbose_name='Diagnosis / Service'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice_item_diagnosis_text',
            field=models.CharField(editable=False, max_length=255, verbose_name='Diagnosis text (snapshot)'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice_item_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice', verbose_name='Invoice'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice_item_line_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Line total (€)'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice_item_pos',
            field=models.PositiveIntegerField(editable=False, null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice_item_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice_item_unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit price (€)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_role',
            field=models.CharField(max_length=32, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
