# Generated by Django 5.2.9 on 2025-12-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnose',
            name='diagnose_title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
