# Generated by Django 5.2.9 on 2025-12-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ['invoice_item_pos']},
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice_item_pos',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
