# Generated by Django 5.2.9 on 2025-12-27 22:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'verbose_name': 'diagnose', 'verbose_name_plural': 'Diagnosen'},
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_customer_id',
            new_name='invoice_customer',
        ),
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='invoice_item_diagnosis',
            new_name='invoice_item_diagnosis',
        ),
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='invoice_item_invoice_id',
            new_name='invoice_item_invoice',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_order_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_service_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice_item_pos',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
