# Generated by Django 4.2.3 on 2026-02-09 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_company_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_order_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Order Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_service_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Service Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_vat_percent',
            field=models.DecimalField(decimal_places=2, default=19.0, max_digits=5, verbose_name='VAT'),
        ),
    ]
