# Generated by Django 4.2.3 on 2026-02-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_invoice_invoice_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Mechanic', 'Mechanic'), ('Accountant', 'Accountant')], max_length=32, verbose_name='Role'),
        ),
    ]
