# Generated by Django 4.2.3 on 2026-02-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_profile_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_bic',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='BIC'),
        ),
    ]
