# Generated by Django 4.2.3 on 2026-02-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_company_company_bic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Mechanic', 'Mechanic'), ('Accountant', 'Accountant')], default='Mechanic', max_length=32, verbose_name='Role'),
        ),
    ]
