# Generated by Django 4.2.3 on 2026-02-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_alter_profile_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice_item_custom_text',
            field=models.CharField(blank=True, help_text='If you enter custom text, it will be used instead of selecting from list.', max_length=255, null=True, verbose_name='Custom diagnosis text'),
        ),
    ]
